name: amazon_clone
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"


#--------------PACKAGES-------------#
dependencies:
  flutter:
    sdk: flutter


  # ICONS
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  get: ^4.6.6




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  